Add a Bounty Proposal for Implementing Claimable Balances in the Account Viewer
tyvdh/stellar-quest-bounties pull request #115
Opened 2021-08-19 17:16 UTC by MatejMecka

Let's improve it further :D

2021-08-19 17:30 UTC, hanseartic commented
I am missing one hint (which may turn out as the main task): The SDK currently has no support for verification of the predicates.It would be desirable to only display claimable balances that are currently claimable instead of firing off to horizon all balances selected by the user.
Ideally balances that won't be claimable anymore (e.g. predicate allowed claiming in the past) don't show up at all and balances that are not claimable yet, but will be in the future show up in a deactivated state.

2021-08-19 17:36 UTC, ElliotFriend requested changes
Looks really good! Great bounty!

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +The Account Viewer is built with React and Typescript. Along with that keep in mind of the existing design guidelines and make sure it's understandable to the user.
```suggestion
The Account Viewer is built with React and TypeScript. Along with that keep in mind the existing design guidelines and make sure it's understandable to the user.
```

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +- The hunter submits a pull request to account-viewer-2
```suggestion
- The hunter submits a pull request to the `account-viewer-2` repository.
```

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +- Any third parties they need to communicate with?
I think these lines got left in from the bounty template.

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +The stellar account viewer is a great tool that allows you to see how many XLM you own, the transactions you received and the option to send payments.
Since the account viewer is so central to this bounty, we might want to have links to the account viewer website and repository up here, as well.

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +- When the Pull Request is merged only then is the bounty completed.
```suggestion
- The bounty will only be considered complete, after the Pull Request has been merged into the main repository.
```

I think this makes it a bit easier to read?

2021-08-19 17:36 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +- Any third parties they need to communicate with?
Does somebody need to communicate with the account-viewer-2 maintainer? Are we sure they're open to this feature? (Just asking for clarity's sake Hehehe)

2021-08-19 17:39 UTC, ElliotFriend commented
> I am missing one hint (which may turn out as the main task): The SDK currently has no support for verification of the predicates.It would be desirable to only display claimable balances that are currently claimable instead of firing off to horizon all balances selected by the user.
> Ideally balances that won't be claimable anymore (e.g. predicate allowed claiming in the past) don't show up at all and balances that are not claimable yet, but will be in the future show up in a deactivated state.

Really good points! Would it ever be useful to see the unclaimable claimable balances? (like, "view your missed pending transactions"?) If so, could it be an additional setting to be implemented?

2021-08-19 18:28 UTC, hanseartic commented
Please also create a new [issue to track](https://github.com/tyvdh/stellar-quest-bounties/issues/new?assignees=&labels=&template=begin-the-hunt.yml&link=https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md&title=Add+Bounty:+Claimable+Balances+in+the+Account+Viewer) the bounty and add a link to this PR in the text-section (Provide relevant details):
![grafik](https://user-images.githubusercontent.com/1752217/130124160-5aa3dba9-158f-4aca-a291-0fd940e7ea3c.png)

2021-08-19 19:52 UTC, tyvdh requested changes
I love this, but in the off chance the AV team isn't interested let's not require a PR on the main interface, just clone it and add the functionality yourself on your own hosted domain. You can open a PR but they're pretty strict over there on what they accept.

This Discussion is similar https://github.com/tyvdh/stellar-quest-bounties/discussions/81

Great start!

2021-08-19 19:52 UTC, tyvdh commented on bounties/level-1/claimable_balances_account_viewer.md
> +| 1000 XLM | 500 XLM | Competitive |
Let's do 1500 XLM and 800 XLM, this one will be a little more difficult.

2021-08-19 20:51 UTC, ElliotFriend reviewed
Looks pretty good. Depending on where the discussion of "merged pull request" vs "implemented in a fork" lands, I think it's quite close.

2021-08-19 20:51 UTC, ElliotFriend commented on bounties/level-1/claimable_balances_account_viewer.md
> +2) New section that will list all pending claimable balances and allow for their claimant
```suggestion
2) New section that will list all pending claimable balances and allow for claiming them.
```

2021-09-01 09:04 UTC, hanseartic approved these changes
Good to go from my side! 🚀

2021-09-01 13:39 UTC, ElliotFriend commented
Looks good over here! 👍

2021-12-15 14:49 UTC, tyvdh commented on bounties/level-1/claimable_balances_account_viewer.md
> +| 1500 XLM | 800 XLM | Competitive |
```suggestion
| 1500 XLM | 800 XLM | Capped (1) | 
```

2021-12-15 14:50 UTC, tyvdh requested changes
Tiny tweak and then this is complete. Make sure to submit the create or link the meta create a bounty bounty

2021-12-15 23:33 UTC, merged