Add bounty for suggesting bounties.
tyvdh/stellar-quest-bounties pull request #13
Opened 2021-07-28 16:09 UTC by Smephite

2021-07-29 14:39 UTC, tyvdh requested changes
This PR is likely dependent on the bounty template PR being completed and accepted first as this would be necessary before more folks start suggesting bounties. So this bounty should likely link to that bounty with the idea that one needs to be completed first.

2021-07-29 14:39 UTC, tyvdh commented on bounties/level-1/create-bounties.md
> +| 500 XLM per bounty | 0 Credits (success will be determined by PR acceptance)
Let's decrease this to 200 XLM. Bounties haven't been as tricky to create as I first suspected. I'll honor the 500 XLM retrospectively but ongoing this should be lower.

2021-07-29 16:15 UTC, ralphilius commented
What about criteria to decide bounty prize and credits? Size of impact? Or size of effort?

2021-07-29 17:13 UTC, Smephite commented
I'd say size of effort

2021-08-02 18:34 UTC, tyvdh requested changes
Would you mind making the necessary adjustments such to meet with our new standards as detailed here? https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/README.md

If there are things missing from that standard please make update requests in this issue https://github.com/tyvdh/stellar-quest-bounties/issues/40 first.

Thanks! Looking forward to getting everyone paid for all their great bounty suggestions over the past couple weeks.

2021-08-03 13:13 UTC, tyvdh requested changes
Really nice! Just a couple more items and I think we're _finally_ ready to ship this!

2021-08-03 13:13 UTC, tyvdh commented on bounties/level-1/create-bounties.md
> +https://github.com/tyvdh/stellar-quest-bounties/issues?q=create-bounties.md
Let's exclude the .md suffix just in the chance folks don't use the .md extension.

2021-08-03 13:13 UTC, tyvdh commented on bounties/level-1/create-bounties.md
> +Overall there is a lot of freedom regarding possible quests therefor: be creative!
therefor -> therefore 😁 

https://www.grammarly.com/blog/therefore-vs-therefor/?&utm_source=google&utm_medium=cpc&utm_campaign=10273012991&utm_targetid=aud-630734890445:dsa-1233402314764&gclid=CjwKCAjw0qOIBhBhEiwAyvVcf4GpBFE-wJcW3LksecGGpnotF0EzlzA5NVuJSc-9u9q6bk3R6HO6iBoCu_IQAvD_BwE&gclsrc=aw.ds

2021-08-03 13:13 UTC, tyvdh commented on bounties/level-1/create-bounties.md
> +- https://github.com/tyvdh/stellar-quest-bounties/pull/9
Just for beauty sake let's format this consistently with spacing. Line 41 butts right against 42, there should be a space. 43 has a tab, 47, 50 and 51 do not. There's a space between ##Links and the first link but that pattern isn't used elsewhere. I'm a stickler for clean consistent code.

2021-08-03 13:37 UTC, Smephite commented on bounties/level-1/create-bounties.md
> +Overall there is a lot of freedom regarding possible quests therefor: be creative!
Still confused but 🤷 🤣

2021-08-03 13:54 UTC, merged